export const refreshTokenKey = "refresk_token_call"
export const fetchSavedHops = "fetch_saved_hops"
export const fetchPublishedHopsFromLink = "fetch_published_hops_from_link"
export const fetchPublishedHops = "fetch_publised_hops"
export const fetchSingleSavedHop = "fetch_single_saved_hop"